@startuml
actor Użytkownik
control MyGUI
entity ModelNN
entity TextExtractor

Użytkownik -> MyGUI: przekaż obrazek z tekstem
MyGUI <- Użytkownik: pokaż okno wyboru plików
Użytkownik -> MyGUI: wybierz plik
MyGUI -> ModelNN: wczytaj model sieci neuronowej
MyGUI -> TextExtractor: wczytaj obiekt o odpowiednich parametrach
MyGUI -> MyGUI: wyrównaj tekst
MyGUI -> TextExtractor: przekaż obrazek
MyGUI <- TextExtractor: pobierz obrazek
MyGUI -> MyGUI: uzupełnij pola tekstowe w aplikacji
MyGUI <- Użytkownik: wyświetl tekst
@enduml