@startuml
actor Użytkownik
control myGUI
entity ModelNN
entity TextExtractor

Użytkownik -> myGUI: przekaż obrazek z tekstem
myGUI <- Użytkownik: pokaż okno wyboru plików
Użytkownik -> myGUI: wybierz plik
myGUI -> ModelNN: wczytaj model sieci neuronowej
myGUI -> TextExtractor: wczytaj obiekt o odpowiednich parametrach
myGUI -> myGUI: wyrównaj tekst
myGUI -> TextExtractor: przekaż obrazek
myGUI <- TextExtractor: pobierz obrazek
myGUI -> myGUI: uzupełnij pola tekstowe w aplikacji
myGUI <- Użytkownik: wyświetl tekst
@enduml