# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkuczaj/Praca_inzynierska/VariousMLTforOCR/gui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 550)
        MainWindow.setMinimumSize(QtCore.QSize(550, 550))
        MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxLoadImage = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxLoadImage.sizePolicy().hasHeightForWidth())
        self.groupBoxLoadImage.setSizePolicy(sizePolicy)
        self.groupBoxLoadImage.setMinimumSize(QtCore.QSize(247, 242))
        self.groupBoxLoadImage.setObjectName("groupBoxLoadImage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxLoadImage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelImage = QtWidgets.QLabel(self.groupBoxLoadImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(220, 200))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.gridLayout_3.addWidget(self.labelImage, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxLoadImage, 0, 0, 1, 1)
        self.groupBoxTextOCR = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTextOCR.sizePolicy().hasHeightForWidth())
        self.groupBoxTextOCR.setSizePolicy(sizePolicy)
        self.groupBoxTextOCR.setMinimumSize(QtCore.QSize(246, 241))
        self.groupBoxTextOCR.setObjectName("groupBoxTextOCR")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBoxTextOCR)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBoxTextOCR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxTextOCR, 1, 1, 1, 1)
        self.groupBoxImageAfterOCR = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxImageAfterOCR.sizePolicy().hasHeightForWidth())
        self.groupBoxImageAfterOCR.setSizePolicy(sizePolicy)
        self.groupBoxImageAfterOCR.setMinimumSize(QtCore.QSize(247, 241))
        self.groupBoxImageAfterOCR.setObjectName("groupBoxImageAfterOCR")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxImageAfterOCR)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelImageAfterOCR = QtWidgets.QLabel(self.groupBoxImageAfterOCR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImageAfterOCR.sizePolicy().hasHeightForWidth())
        self.labelImageAfterOCR.setSizePolicy(sizePolicy)
        self.labelImageAfterOCR.setMinimumSize(QtCore.QSize(220, 200))
        self.labelImageAfterOCR.setText("")
        self.labelImageAfterOCR.setObjectName("labelImageAfterOCR")
        self.gridLayout_4.addWidget(self.labelImageAfterOCR, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxImageAfterOCR, 1, 0, 1, 1)
        self.groupBoxController = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxController.sizePolicy().hasHeightForWidth())
        self.groupBoxController.setSizePolicy(sizePolicy)
        self.groupBoxController.setMinimumSize(QtCore.QSize(246, 242))
        self.groupBoxController.setObjectName("groupBoxController")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxController)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAlgorithmChoice = QtWidgets.QLabel(self.groupBoxController)
        self.labelAlgorithmChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAlgorithmChoice.setObjectName("labelAlgorithmChoice")
        self.verticalLayout.addWidget(self.labelAlgorithmChoice)
        self.comboBoxAlgorithms = QtWidgets.QComboBox(self.groupBoxController)
        self.comboBoxAlgorithms.setObjectName("comboBoxAlgorithms")
        self.verticalLayout.addWidget(self.comboBoxAlgorithms)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSliderMaxH = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMaxH.setMinimum(100)
        self.horizontalSliderMaxH.setMaximum(200)
        self.horizontalSliderMaxH.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxH.setObjectName("horizontalSliderMaxH")
        self.horizontalLayout_2.addWidget(self.horizontalSliderMaxH)
        self.labelMaxH = QtWidgets.QLabel(self.groupBoxController)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMaxH.sizePolicy().hasHeightForWidth())
        self.labelMaxH.setSizePolicy(sizePolicy)
        self.labelMaxH.setObjectName("labelMaxH")
        self.horizontalLayout_2.addWidget(self.labelMaxH)
        self.lcdmaxH = QtWidgets.QLCDNumber(self.groupBoxController)
        self.lcdmaxH.setObjectName("lcdmaxH")
        self.horizontalLayout_2.addWidget(self.lcdmaxH)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSliderMinH = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMinH.setMinimum(0)
        self.horizontalSliderMinH.setMaximum(100)
        self.horizontalSliderMinH.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinH.setObjectName("horizontalSliderMinH")
        self.horizontalLayout_4.addWidget(self.horizontalSliderMinH)
        self.labelMinH = QtWidgets.QLabel(self.groupBoxController)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMinH.sizePolicy().hasHeightForWidth())
        self.labelMinH.setSizePolicy(sizePolicy)
        self.labelMinH.setText("")
        self.labelMinH.setPixmap(QtGui.QPixmap("../../../Pictures/img002-00001.png"))
        self.labelMinH.setObjectName("labelMinH")
        self.horizontalLayout_4.addWidget(self.labelMinH)
        self.lcdminH = QtWidgets.QLCDNumber(self.groupBoxController)
        self.lcdminH.setObjectName("lcdminH")
        self.horizontalLayout_4.addWidget(self.lcdminH)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSliderMaxW = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMaxW.setMinimum(10)
        self.horizontalSliderMaxW.setMaximum(80)
        self.horizontalSliderMaxW.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxW.setObjectName("horizontalSliderMaxW")
        self.horizontalLayout_3.addWidget(self.horizontalSliderMaxW)
        self.labelMaxW = QtWidgets.QLabel(self.groupBoxController)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMaxW.sizePolicy().hasHeightForWidth())
        self.labelMaxW.setSizePolicy(sizePolicy)
        self.labelMaxW.setObjectName("labelMaxW")
        self.horizontalLayout_3.addWidget(self.labelMaxW)
        self.lcdmaxW = QtWidgets.QLCDNumber(self.groupBoxController)
        self.lcdmaxW.setObjectName("lcdmaxW")
        self.horizontalLayout_3.addWidget(self.lcdmaxW)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalSliderMinW = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMinW.setMinimum(10)
        self.horizontalSliderMinW.setMaximum(40)
        self.horizontalSliderMinW.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinW.setObjectName("horizontalSliderMinW")
        self.horizontalLayout_6.addWidget(self.horizontalSliderMinW)
        self.labelMinW = QtWidgets.QLabel(self.groupBoxController)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMinW.sizePolicy().hasHeightForWidth())
        self.labelMinW.setSizePolicy(sizePolicy)
        self.labelMinW.setObjectName("labelMinW")
        self.horizontalLayout_6.addWidget(self.labelMinW)
        self.lcdminW = QtWidgets.QLCDNumber(self.groupBoxController)
        self.lcdminW.setObjectName("lcdminW")
        self.horizontalLayout_6.addWidget(self.lcdminW)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonLoadFile = QtWidgets.QPushButton(self.groupBoxController)
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        self.horizontalLayout.addWidget(self.pushButtonLoadFile)
        self.pushButtonCamera = QtWidgets.QPushButton(self.groupBoxController)
        self.pushButtonCamera.setObjectName("pushButtonCamera")
        self.horizontalLayout.addWidget(self.pushButtonCamera)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxController, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Various Machine Learning Techniques for OCR"))
        self.groupBoxLoadImage.setTitle(_translate("MainWindow", "Loaded Image"))
        self.groupBoxTextOCR.setTitle(_translate("MainWindow", "Recognized Text"))
        self.groupBoxImageAfterOCR.setTitle(_translate("MainWindow", "Image after recognition"))
        self.groupBoxController.setTitle(_translate("MainWindow", "Menu"))
        self.labelAlgorithmChoice.setText(_translate("MainWindow", "Choose an algorithm"))
        self.labelMaxH.setText(_translate("MainWindow", "maxH"))
        self.labelMaxW.setText(_translate("MainWindow", "maxW"))
        self.labelMinW.setText(_translate("MainWindow", "minW"))
        self.pushButtonLoadFile.setToolTip(_translate("MainWindow", "Load images you want to recognize characters in"))
        self.pushButtonLoadFile.setText(_translate("MainWindow", "Load File"))
        self.pushButtonCamera.setToolTip(_translate("MainWindow", "Load images you want to recognize characters in"))
        self.pushButtonCamera.setText(_translate("MainWindow", "Camera"))

