# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkuczaj/Praca_inzynierska/VariousMLTforOCR/gui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 820)
        MainWindow.setMinimumSize(QtCore.QSize(550, 550))
        MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxLoadImage = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxLoadImage.sizePolicy().hasHeightForWidth())
        self.groupBoxLoadImage.setSizePolicy(sizePolicy)
        self.groupBoxLoadImage.setMinimumSize(QtCore.QSize(247, 242))
        self.groupBoxLoadImage.setObjectName("groupBoxLoadImage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxLoadImage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelImage = QtWidgets.QLabel(self.groupBoxLoadImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(220, 200))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.gridLayout_3.addWidget(self.labelImage, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxLoadImage, 0, 0, 1, 1)
        self.groupBoxTextOCR = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTextOCR.sizePolicy().hasHeightForWidth())
        self.groupBoxTextOCR.setSizePolicy(sizePolicy)
        self.groupBoxTextOCR.setMinimumSize(QtCore.QSize(246, 241))
        self.groupBoxTextOCR.setObjectName("groupBoxTextOCR")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBoxTextOCR)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBoxTextOCR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxTextOCR, 1, 1, 1, 1)
        self.groupBoxImageAfterOCR = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxImageAfterOCR.sizePolicy().hasHeightForWidth())
        self.groupBoxImageAfterOCR.setSizePolicy(sizePolicy)
        self.groupBoxImageAfterOCR.setMinimumSize(QtCore.QSize(247, 241))
        self.groupBoxImageAfterOCR.setObjectName("groupBoxImageAfterOCR")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxImageAfterOCR)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelImageAfterOCR = QtWidgets.QLabel(self.groupBoxImageAfterOCR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImageAfterOCR.sizePolicy().hasHeightForWidth())
        self.labelImageAfterOCR.setSizePolicy(sizePolicy)
        self.labelImageAfterOCR.setMinimumSize(QtCore.QSize(220, 200))
        self.labelImageAfterOCR.setText("")
        self.labelImageAfterOCR.setObjectName("labelImageAfterOCR")
        self.gridLayout_4.addWidget(self.labelImageAfterOCR, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxImageAfterOCR, 1, 0, 1, 1)
        self.groupBoxController = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxController.sizePolicy().hasHeightForWidth())
        self.groupBoxController.setSizePolicy(sizePolicy)
        self.groupBoxController.setMinimumSize(QtCore.QSize(246, 242))
        self.groupBoxController.setAutoFillBackground(False)
        self.groupBoxController.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(0, 120, 255, 120), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:0, y1:0, stop:0 rgba(0, 120, 255, 120), stop:1 rgba(255, 255, 255, 255));")
        self.groupBoxController.setObjectName("groupBoxController")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxController)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_segmentation = QtWidgets.QGroupBox(self.groupBoxController)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_segmentation.setFont(font)
        self.groupBox_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_segmentation.setObjectName("groupBox_segmentation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_segmentation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_maxH = QtWidgets.QHBoxLayout()
        self.horizontalLayout_maxH.setObjectName("horizontalLayout_maxH")
        self.horizontalSliderMaxH = QtWidgets.QSlider(self.groupBox_segmentation)
        self.horizontalSliderMaxH.setMinimum(100)
        self.horizontalSliderMaxH.setMaximum(200)
        self.horizontalSliderMaxH.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxH.setObjectName("horizontalSliderMaxH")
        self.horizontalLayout_maxH.addWidget(self.horizontalSliderMaxH)
        self.labelMaxH = QtWidgets.QLabel(self.groupBox_segmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMaxH.sizePolicy().hasHeightForWidth())
        self.labelMaxH.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelMaxH.setFont(font)
        self.labelMaxH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelMaxH.setObjectName("labelMaxH")
        self.horizontalLayout_maxH.addWidget(self.labelMaxH)
        self.lcdmaxH = QtWidgets.QLCDNumber(self.groupBox_segmentation)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lcdmaxH.setFont(font)
        self.lcdmaxH.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.lcdmaxH.setObjectName("lcdmaxH")
        self.horizontalLayout_maxH.addWidget(self.lcdmaxH)
        self.verticalLayout_2.addLayout(self.horizontalLayout_maxH)
        self.horizontalLayout_minH = QtWidgets.QHBoxLayout()
        self.horizontalLayout_minH.setObjectName("horizontalLayout_minH")
        self.horizontalSliderMinH = QtWidgets.QSlider(self.groupBox_segmentation)
        self.horizontalSliderMinH.setMinimum(0)
        self.horizontalSliderMinH.setMaximum(100)
        self.horizontalSliderMinH.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinH.setObjectName("horizontalSliderMinH")
        self.horizontalLayout_minH.addWidget(self.horizontalSliderMinH)
        self.labelMinH = QtWidgets.QLabel(self.groupBox_segmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMinH.sizePolicy().hasHeightForWidth())
        self.labelMinH.setSizePolicy(sizePolicy)
        self.labelMinH.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelMinH.setFont(font)
        self.labelMinH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelMinH.setObjectName("labelMinH")
        self.horizontalLayout_minH.addWidget(self.labelMinH)
        self.lcdminH = QtWidgets.QLCDNumber(self.groupBox_segmentation)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lcdminH.setFont(font)
        self.lcdminH.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.lcdminH.setObjectName("lcdminH")
        self.horizontalLayout_minH.addWidget(self.lcdminH)
        self.verticalLayout_2.addLayout(self.horizontalLayout_minH)
        self.horizontalLayout_maxW = QtWidgets.QHBoxLayout()
        self.horizontalLayout_maxW.setObjectName("horizontalLayout_maxW")
        self.horizontalSliderMaxW = QtWidgets.QSlider(self.groupBox_segmentation)
        self.horizontalSliderMaxW.setMinimum(40)
        self.horizontalSliderMaxW.setMaximum(80)
        self.horizontalSliderMaxW.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxW.setObjectName("horizontalSliderMaxW")
        self.horizontalLayout_maxW.addWidget(self.horizontalSliderMaxW)
        self.labelMaxW = QtWidgets.QLabel(self.groupBox_segmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMaxW.sizePolicy().hasHeightForWidth())
        self.labelMaxW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelMaxW.setFont(font)
        self.labelMaxW.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelMaxW.setObjectName("labelMaxW")
        self.horizontalLayout_maxW.addWidget(self.labelMaxW)
        self.lcdmaxW = QtWidgets.QLCDNumber(self.groupBox_segmentation)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lcdmaxW.setFont(font)
        self.lcdmaxW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.lcdmaxW.setObjectName("lcdmaxW")
        self.horizontalLayout_maxW.addWidget(self.lcdmaxW)
        self.verticalLayout_2.addLayout(self.horizontalLayout_maxW)
        self.horizontalLayout_minW = QtWidgets.QHBoxLayout()
        self.horizontalLayout_minW.setObjectName("horizontalLayout_minW")
        self.horizontalSliderMinW = QtWidgets.QSlider(self.groupBox_segmentation)
        self.horizontalSliderMinW.setMinimum(10)
        self.horizontalSliderMinW.setMaximum(40)
        self.horizontalSliderMinW.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinW.setObjectName("horizontalSliderMinW")
        self.horizontalLayout_minW.addWidget(self.horizontalSliderMinW)
        self.labelMinW = QtWidgets.QLabel(self.groupBox_segmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMinW.sizePolicy().hasHeightForWidth())
        self.labelMinW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelMinW.setFont(font)
        self.labelMinW.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelMinW.setObjectName("labelMinW")
        self.horizontalLayout_minW.addWidget(self.labelMinW)
        self.lcdminW = QtWidgets.QLCDNumber(self.groupBox_segmentation)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lcdminW.setFont(font)
        self.lcdminW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.lcdminW.setObjectName("lcdminW")
        self.horizontalLayout_minW.addWidget(self.lcdminW)
        self.verticalLayout_2.addLayout(self.horizontalLayout_minW)
        self.verticalLayout_3.addWidget(self.groupBox_segmentation)
        self.groupBox = QtWidgets.QGroupBox(self.groupBoxController)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAlgorithmChoice = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelAlgorithmChoice.setFont(font)
        self.labelAlgorithmChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAlgorithmChoice.setObjectName("labelAlgorithmChoice")
        self.verticalLayout.addWidget(self.labelAlgorithmChoice)
        self.comboBoxAlgorithms = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxAlgorithms.setFont(font)
        self.comboBoxAlgorithms.setAutoFillBackground(False)
        self.comboBoxAlgorithms.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.comboBoxAlgorithms.setObjectName("comboBoxAlgorithms")
        self.verticalLayout.addWidget(self.comboBoxAlgorithms)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonLoadFile = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLoadFile.setFont(font)
        self.pushButtonLoadFile.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        self.horizontalLayout.addWidget(self.pushButtonLoadFile)
        self.pushButton_doOCR = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_doOCR.setFont(font)
        self.pushButton_doOCR.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_doOCR.setObjectName("pushButton_doOCR")
        self.horizontalLayout.addWidget(self.pushButton_doOCR)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.groupBoxController, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Various Machine Learning Techniques for OCR"))
        self.groupBoxLoadImage.setTitle(_translate("MainWindow", "Loaded Image"))
        self.groupBoxTextOCR.setTitle(_translate("MainWindow", "Recognized Text"))
        self.groupBoxImageAfterOCR.setTitle(_translate("MainWindow", "Image after recognition"))
        self.groupBoxController.setTitle(_translate("MainWindow", "Menu"))
        self.groupBox_segmentation.setTitle(_translate("MainWindow", "Image Segmentation"))
        self.labelMaxH.setText(_translate("MainWindow", "maxH"))
        self.labelMinH.setText(_translate("MainWindow", "minH"))
        self.labelMaxW.setText(_translate("MainWindow", "maxW"))
        self.labelMinW.setText(_translate("MainWindow", "minW"))
        self.groupBox.setTitle(_translate("MainWindow", "Algorithm and Loading"))
        self.labelAlgorithmChoice.setText(_translate("MainWindow", "Choose an algorithm"))
        self.pushButtonLoadFile.setToolTip(_translate("MainWindow", "Load images you want to recognize characters in"))
        self.pushButtonLoadFile.setText(_translate("MainWindow", "Load File"))
        self.pushButton_doOCR.setText(_translate("MainWindow", "Recognize"))

