# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkuczaj/Praca_inzynierska/VariousMLTforOCR/gui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 550))
        MainWindow.setMaximumSize(QtCore.QSize(550, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 501, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxController = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxController.sizePolicy().hasHeightForWidth())
        self.groupBoxController.setSizePolicy(sizePolicy)
        self.groupBoxController.setMinimumSize(QtCore.QSize(246, 242))
        self.groupBoxController.setObjectName("groupBoxController")
        self.pushButtonLoadFile = QtWidgets.QPushButton(self.groupBoxController)
        self.pushButtonLoadFile.setGeometry(QtCore.QRect(130, 90, 79, 24))
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        self.pushButtonCamera = QtWidgets.QPushButton(self.groupBoxController)
        self.pushButtonCamera.setGeometry(QtCore.QRect(30, 90, 79, 24))
        self.pushButtonCamera.setObjectName("pushButtonCamera")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBoxController)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 211, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAlgorithmChoice = QtWidgets.QLabel(self.layoutWidget1)
        self.labelAlgorithmChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAlgorithmChoice.setObjectName("labelAlgorithmChoice")
        self.verticalLayout.addWidget(self.labelAlgorithmChoice)
        self.comboBoxAlgorithms = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBoxAlgorithms.setObjectName("comboBoxAlgorithms")
        self.verticalLayout.addWidget(self.comboBoxAlgorithms)
        self.horizontalSliderMaxH = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMaxH.setGeometry(QtCore.QRect(0, 140, 151, 18))
        self.horizontalSliderMaxH.setMinimum(100)
        self.horizontalSliderMaxH.setMaximum(400)
        self.horizontalSliderMaxH.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxH.setObjectName("horizontalSliderMaxH")
        self.horizontalSliderMinH = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMinH.setGeometry(QtCore.QRect(0, 170, 151, 18))
        self.horizontalSliderMinH.setMinimum(100)
        self.horizontalSliderMinH.setMaximum(400)
        self.horizontalSliderMinH.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinH.setObjectName("horizontalSliderMinH")
        self.horizontalSliderMaxW = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMaxW.setGeometry(QtCore.QRect(0, 200, 151, 18))
        self.horizontalSliderMaxW.setMinimum(10)
        self.horizontalSliderMaxW.setMaximum(80)
        self.horizontalSliderMaxW.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxW.setObjectName("horizontalSliderMaxW")
        self.horizontalSliderMinW = QtWidgets.QSlider(self.groupBoxController)
        self.horizontalSliderMinW.setGeometry(QtCore.QRect(0, 220, 151, 18))
        self.horizontalSliderMinW.setMinimum(10)
        self.horizontalSliderMinW.setMaximum(80)
        self.horizontalSliderMinW.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinW.setObjectName("horizontalSliderMinW")
        self.labelMaxH = QtWidgets.QLabel(self.groupBoxController)
        self.labelMaxH.setGeometry(QtCore.QRect(160, 140, 41, 17))
        self.labelMaxH.setObjectName("labelMaxH")
        self.labelMinH = QtWidgets.QLabel(self.groupBoxController)
        self.labelMinH.setGeometry(QtCore.QRect(160, 170, 41, 17))
        self.labelMinH.setObjectName("labelMinH")
        self.labelMaxW = QtWidgets.QLabel(self.groupBoxController)
        self.labelMaxW.setGeometry(QtCore.QRect(160, 200, 41, 17))
        self.labelMaxW.setObjectName("labelMaxW")
        self.labelMinW = QtWidgets.QLabel(self.groupBoxController)
        self.labelMinW.setGeometry(QtCore.QRect(160, 220, 41, 17))
        self.labelMinW.setObjectName("labelMinW")
        self.gridLayout.addWidget(self.groupBoxController, 0, 1, 1, 1)
        self.groupBoxImageAfterOCR = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxImageAfterOCR.setMinimumSize(QtCore.QSize(247, 241))
        self.groupBoxImageAfterOCR.setObjectName("groupBoxImageAfterOCR")
        self.labelImageAfterOCR = QtWidgets.QLabel(self.groupBoxImageAfterOCR)
        self.labelImageAfterOCR.setGeometry(QtCore.QRect(10, 30, 220, 200))
        self.labelImageAfterOCR.setMinimumSize(QtCore.QSize(220, 200))
        self.labelImageAfterOCR.setText("")
        self.labelImageAfterOCR.setObjectName("labelImageAfterOCR")
        self.gridLayout.addWidget(self.groupBoxImageAfterOCR, 1, 0, 1, 1)
        self.groupBoxTextOCR = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxTextOCR.setMinimumSize(QtCore.QSize(246, 241))
        self.groupBoxTextOCR.setObjectName("groupBoxTextOCR")
        self.textEdit = QtWidgets.QTextEdit(self.groupBoxTextOCR)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 221, 201))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.groupBoxTextOCR, 1, 1, 1, 1)
        self.groupBoxLoadImage = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxLoadImage.sizePolicy().hasHeightForWidth())
        self.groupBoxLoadImage.setSizePolicy(sizePolicy)
        self.groupBoxLoadImage.setMinimumSize(QtCore.QSize(247, 242))
        self.groupBoxLoadImage.setObjectName("groupBoxLoadImage")
        self.labelImage = QtWidgets.QLabel(self.groupBoxLoadImage)
        self.labelImage.setGeometry(QtCore.QRect(20, 30, 220, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(220, 200))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.gridLayout.addWidget(self.groupBoxLoadImage, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Various Machine Learning Techniques for OCR"))
        self.groupBoxController.setTitle(_translate("MainWindow", "Menu"))
        self.pushButtonLoadFile.setToolTip(_translate("MainWindow", "Load images you want to recognize characters in"))
        self.pushButtonLoadFile.setText(_translate("MainWindow", "Load File"))
        self.pushButtonCamera.setToolTip(_translate("MainWindow", "Load images you want to recognize characters in"))
        self.pushButtonCamera.setText(_translate("MainWindow", "Camera"))
        self.labelAlgorithmChoice.setText(_translate("MainWindow", "Choose an algorithm"))
        self.labelMaxH.setText(_translate("MainWindow", "maxH"))
        self.labelMinH.setText(_translate("MainWindow", "minH"))
        self.labelMaxW.setText(_translate("MainWindow", "maxW"))
        self.labelMinW.setText(_translate("MainWindow", "minW"))
        self.groupBoxImageAfterOCR.setTitle(_translate("MainWindow", "Image after recognition"))
        self.groupBoxTextOCR.setTitle(_translate("MainWindow", "Recognized Text"))
        self.groupBoxLoadImage.setTitle(_translate("MainWindow", "Loaded Image"))

